//! Generated protobuf and gRPC stubs for the chaffra AnalysisModule service.
//!
//! This crate wraps the code generated by `tonic-build` from
//! `proto/chaffra/module/v1/module.proto` and re-exports all types,
//! the gRPC server trait, and the gRPC client.

/// Generated protobuf types and gRPC stubs.
pub mod proto {
    tonic::include_proto!("chaffra.module.v1");
}
